# --- SHARED MEMORY CONFIG ---
SHM_NAME = "/robot_control_shm"

# Định dạng struct để unpack Feedback (18 doubles)
FB_STRUCT_FORMAT = '18d' 

# OFFSETS (Phải khớp chính xác với C++ ở trên)
OFF_MODE = 144
OFF_TARGET_POS = 152
OFF_TARGET_RPY = 176
OFF_TRAJ_VEL_LIN = 200
OFF_PATH_SIZE = 248
OFF_PATH_POINTS = 256
OFF_TRAJ_DUR = 736
OFF_TRAJ_TRIG = 744
OFF_MANUAL_J = 752
OFF_GRIPPER = 800
OFF_ACTIVE = 808

# Modes
MODE_IDLE = 0
MODE_POSE = 1
MODE_TRAJECTORY = 2
MODE_JOINT = 3

COORD_KEYS = ["X", "Y", "Z", "Roll", "Pitch", "Yaw"]
MAX_ALLOWED_ERROR = 0.05